# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c308f8921d6e5821b465c48dc00b8df478ef84d306ddb993e6fb9dce9b16d38822dee967fcb6fde658781fc8af2d25f39bdeecc9b80bc8e23f423841d86730b7

test:
  secret_key_base: 5fffd64b0ee5d49df121e5862181c446df7d2d59e2aa9efd5661e442664946f40e5d52b79b113248c95dfc88f550d682002521554107fb8d2bf253d16fc27ac5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
